version: '3.8'

services:
  frontend:
    build: .
    container_name: dayzone-frontend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=https://dayzone2-backend-gobqh3-cf2a4b-85-215-53-87.traefik.me/api
      - GENERATE_SOURCEMAP=false
      - CI=false
    ports:
      - "3000:80"
    networks:
      - dayzone_network

networks:
  dayzone_network:
    driver: bridge
